[package]
name = "ldatranslate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ldatranslate"
crate-type = ["cdylib"]


[dependencies]
# Python binding
pyo3 = "0.21"
itertools = "0.13"
thiserror = "1.0"
zip = "1.2"
strum = { version = "0.26", features = ["derive"] }
bimap = "0.6"
delegate = "0.12"
serde = { version = "1.0.202", features = ["derive", "rc"] }
serde_json = "1"
byteorder = "1"
bincode = "1"
flate2 = "1"
regex = "1"
once_cell = "1"
enum_dispatch = "0.3"
approx = "0.5"
rayon = "1"
log = "0.4"
rand = "0.9.0-alpha.1"
rand_distr = "0.5.0-alpha.1"
statrs = "0.16"
string-interner = { version = "0.17", features = ["serde", "std"] }
# https://crates.io/crates/internment
#https://github.com/ISibboI/evalexpr
evalexpr = "11"
nom = "7"
num = "0.4"
num_enum = "0.7"
derive_more = "0.99"
paste = "1.0"
#derive-where = "1.2"

indenter = { version = "0", features = ["std"] }
