[package]
name = "ldatranslate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# https://lib.rs/crates/evalexpr
# https://lib.rs/crates/rusqlite