[package]
name = "ldatranslate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# https://lib.rs/crates/evalexpr
# https://lib.rs/crates/rusqlite

# https://github.com/rust-itertools/itertools
itertools = "0.13"
thiserror = "1.0"
zip = "1.2"
strum = { version = "0.26", features = ["derive"] }
bimap = "0.6"
delegate = "0.12"
serde = { version = "1.0.202", features = ["derive"] }
byteorder = "1"
bincode = "1"
flate2 = "1"
regex = "1"
once_cell = "1"
enum_dispatch = "0.3"
approx = "0.5"
serde_json = "1"